/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vng.zing.statcollect.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ZACollectStatsService {

  public interface Iface {

    public int pushMapStatPoint(TMapStatPoint mapStatPoint) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void pushMapStatPoint(TMapStatPoint mapStatPoint, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.pushMapStatPoint_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public int pushMapStatPoint(TMapStatPoint mapStatPoint) throws org.apache.thrift.TException
    {
      send_pushMapStatPoint(mapStatPoint);
      return recv_pushMapStatPoint();
    }

    public void send_pushMapStatPoint(TMapStatPoint mapStatPoint) throws org.apache.thrift.TException
    {
      pushMapStatPoint_args args = new pushMapStatPoint_args();
      args.setMapStatPoint(mapStatPoint);
      sendBase("pushMapStatPoint", args);
    }

    public int recv_pushMapStatPoint() throws org.apache.thrift.TException
    {
      pushMapStatPoint_result result = new pushMapStatPoint_result();
      receiveBase(result, "pushMapStatPoint");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "pushMapStatPoint failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void pushMapStatPoint(TMapStatPoint mapStatPoint, org.apache.thrift.async.AsyncMethodCallback<pushMapStatPoint_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      pushMapStatPoint_call method_call = new pushMapStatPoint_call(mapStatPoint, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class pushMapStatPoint_call extends org.apache.thrift.async.TAsyncMethodCall {
      private TMapStatPoint mapStatPoint;
      public pushMapStatPoint_call(TMapStatPoint mapStatPoint, org.apache.thrift.async.AsyncMethodCallback<pushMapStatPoint_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.mapStatPoint = mapStatPoint;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("pushMapStatPoint", org.apache.thrift.protocol.TMessageType.CALL, 0));
        pushMapStatPoint_args args = new pushMapStatPoint_args();
        args.setMapStatPoint(mapStatPoint);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public int getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_pushMapStatPoint();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("pushMapStatPoint", new pushMapStatPoint());
      return processMap;
    }

    public static class pushMapStatPoint<I extends Iface> extends org.apache.thrift.ProcessFunction<I, pushMapStatPoint_args> {
      public pushMapStatPoint() {
        super("pushMapStatPoint");
      }

      public pushMapStatPoint_args getEmptyArgsInstance() {
        return new pushMapStatPoint_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public pushMapStatPoint_result getResult(I iface, pushMapStatPoint_args args) throws org.apache.thrift.TException {
        pushMapStatPoint_result result = new pushMapStatPoint_result();
        result.success = iface.pushMapStatPoint(args.mapStatPoint);
        result.setSuccessIsSet(true);
        return result;
      }
    }

  }

  public static class pushMapStatPoint_args implements org.apache.thrift.TBase<pushMapStatPoint_args, pushMapStatPoint_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("pushMapStatPoint_args");

    private static final org.apache.thrift.protocol.TField MAP_STAT_POINT_FIELD_DESC = new org.apache.thrift.protocol.TField("mapStatPoint", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new pushMapStatPoint_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new pushMapStatPoint_argsTupleSchemeFactory());
    }

    public TMapStatPoint mapStatPoint; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      MAP_STAT_POINT((short)1, "mapStatPoint");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // MAP_STAT_POINT
            return MAP_STAT_POINT;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.MAP_STAT_POINT, new org.apache.thrift.meta_data.FieldMetaData("mapStatPoint", org.apache.thrift.TFieldRequirementType.REQUIRED, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TMapStatPoint.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(pushMapStatPoint_args.class, metaDataMap);
    }

    public pushMapStatPoint_args() {
    }

    public pushMapStatPoint_args(
      TMapStatPoint mapStatPoint)
    {
      this();
      this.mapStatPoint = mapStatPoint;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public pushMapStatPoint_args(pushMapStatPoint_args other) {
      if (other.isSetMapStatPoint()) {
        this.mapStatPoint = new TMapStatPoint(other.mapStatPoint);
      }
    }

    public pushMapStatPoint_args deepCopy() {
      return new pushMapStatPoint_args(this);
    }

    @Override
    public void clear() {
      this.mapStatPoint = null;
    }

    public TMapStatPoint getMapStatPoint() {
      return this.mapStatPoint;
    }

    public pushMapStatPoint_args setMapStatPoint(TMapStatPoint mapStatPoint) {
      this.mapStatPoint = mapStatPoint;
      return this;
    }

    public void unsetMapStatPoint() {
      this.mapStatPoint = null;
    }

    /** Returns true if field mapStatPoint is set (has been assigned a value) and false otherwise */
    public boolean isSetMapStatPoint() {
      return this.mapStatPoint != null;
    }

    public void setMapStatPointIsSet(boolean value) {
      if (!value) {
        this.mapStatPoint = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case MAP_STAT_POINT:
        if (value == null) {
          unsetMapStatPoint();
        } else {
          setMapStatPoint((TMapStatPoint)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case MAP_STAT_POINT:
        return getMapStatPoint();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case MAP_STAT_POINT:
        return isSetMapStatPoint();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof pushMapStatPoint_args)
        return this.equals((pushMapStatPoint_args)that);
      return false;
    }

    public boolean equals(pushMapStatPoint_args that) {
      if (that == null)
        return false;

      boolean this_present_mapStatPoint = true && this.isSetMapStatPoint();
      boolean that_present_mapStatPoint = true && that.isSetMapStatPoint();
      if (this_present_mapStatPoint || that_present_mapStatPoint) {
        if (!(this_present_mapStatPoint && that_present_mapStatPoint))
          return false;
        if (!this.mapStatPoint.equals(that.mapStatPoint))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(pushMapStatPoint_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      pushMapStatPoint_args typedOther = (pushMapStatPoint_args)other;

      lastComparison = Boolean.valueOf(isSetMapStatPoint()).compareTo(typedOther.isSetMapStatPoint());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetMapStatPoint()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mapStatPoint, typedOther.mapStatPoint);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("pushMapStatPoint_args(");
      boolean first = true;

      sb.append("mapStatPoint:");
      if (this.mapStatPoint == null) {
        sb.append("null");
      } else {
        sb.append(this.mapStatPoint);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      if (mapStatPoint == null) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'mapStatPoint' was not present! Struct: " + toString());
      }
      // check for sub-struct validity
      if (mapStatPoint != null) {
        mapStatPoint.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class pushMapStatPoint_argsStandardSchemeFactory implements SchemeFactory {
      public pushMapStatPoint_argsStandardScheme getScheme() {
        return new pushMapStatPoint_argsStandardScheme();
      }
    }

    private static class pushMapStatPoint_argsStandardScheme extends StandardScheme<pushMapStatPoint_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, pushMapStatPoint_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // MAP_STAT_POINT
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.mapStatPoint = new TMapStatPoint();
                struct.mapStatPoint.read(iprot);
                struct.setMapStatPointIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, pushMapStatPoint_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.mapStatPoint != null) {
          oprot.writeFieldBegin(MAP_STAT_POINT_FIELD_DESC);
          struct.mapStatPoint.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class pushMapStatPoint_argsTupleSchemeFactory implements SchemeFactory {
      public pushMapStatPoint_argsTupleScheme getScheme() {
        return new pushMapStatPoint_argsTupleScheme();
      }
    }

    private static class pushMapStatPoint_argsTupleScheme extends TupleScheme<pushMapStatPoint_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, pushMapStatPoint_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        struct.mapStatPoint.write(oprot);
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, pushMapStatPoint_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        struct.mapStatPoint = new TMapStatPoint();
        struct.mapStatPoint.read(iprot);
        struct.setMapStatPointIsSet(true);
      }
    }

  }

  public static class pushMapStatPoint_result implements org.apache.thrift.TBase<pushMapStatPoint_result, pushMapStatPoint_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("pushMapStatPoint_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.I32, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new pushMapStatPoint_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new pushMapStatPoint_resultTupleSchemeFactory());
    }

    public int success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __SUCCESS_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(pushMapStatPoint_result.class, metaDataMap);
    }

    public pushMapStatPoint_result() {
    }

    public pushMapStatPoint_result(
      int success)
    {
      this();
      this.success = success;
      setSuccessIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public pushMapStatPoint_result(pushMapStatPoint_result other) {
      __isset_bitfield = other.__isset_bitfield;
      this.success = other.success;
    }

    public pushMapStatPoint_result deepCopy() {
      return new pushMapStatPoint_result(this);
    }

    @Override
    public void clear() {
      setSuccessIsSet(false);
      this.success = 0;
    }

    public int getSuccess() {
      return this.success;
    }

    public pushMapStatPoint_result setSuccess(int success) {
      this.success = success;
      setSuccessIsSet(true);
      return this;
    }

    public void unsetSuccess() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    public void setSuccessIsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Integer)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return Integer.valueOf(getSuccess());

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof pushMapStatPoint_result)
        return this.equals((pushMapStatPoint_result)that);
      return false;
    }

    public boolean equals(pushMapStatPoint_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true;
      boolean that_present_success = true;
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (this.success != that.success)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(pushMapStatPoint_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      pushMapStatPoint_result typedOther = (pushMapStatPoint_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("pushMapStatPoint_result(");
      boolean first = true;

      sb.append("success:");
      sb.append(this.success);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class pushMapStatPoint_resultStandardSchemeFactory implements SchemeFactory {
      public pushMapStatPoint_resultStandardScheme getScheme() {
        return new pushMapStatPoint_resultStandardScheme();
      }
    }

    private static class pushMapStatPoint_resultStandardScheme extends StandardScheme<pushMapStatPoint_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, pushMapStatPoint_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.success = iprot.readI32();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, pushMapStatPoint_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.isSetSuccess()) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeI32(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class pushMapStatPoint_resultTupleSchemeFactory implements SchemeFactory {
      public pushMapStatPoint_resultTupleScheme getScheme() {
        return new pushMapStatPoint_resultTupleScheme();
      }
    }

    private static class pushMapStatPoint_resultTupleScheme extends TupleScheme<pushMapStatPoint_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, pushMapStatPoint_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeI32(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, pushMapStatPoint_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readI32();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
